name: Create release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get-version
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ github.ref }}
          find: 'refs/tags/v'
          replace: ''

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.get-version.outputs.value }}
          draft: false
          prerelease: false
